import React, { useCallback, useMemo } from 'react';
import { Edit, TextInput, SimpleForm, required } from 'react-admin';

const ProfileEdit = ({ staticContext, ...props }) => {
    return (
        <Edit
            /*
                As we are not coming for a route generated by a Resource component,
                we have to provide the id ourselves.
                As there is only one config for the current user, we decided to
                hardcode it here
                Ponieważ nie idziemy po trasę wygenerowaną przez komponent Resource,
                musimy sami dostarczyć identyfikator.
                Ponieważ dla bieżącego użytkownika jest tylko jedna konfiguracja, postanowiliśmy
                zakoduj to tutaj
            */
            id="User12356x"
            /*
                For the same reason, we need to provide the resource and basePath props
                which are required by the Edit component
                Z tego samego powodu musimy podać właściwości zasobu i basePath
                które są wymagane przez komponent Edit
            */
            resource="datauser"
            basePath="/datauser"
            redirect={false}
            title="My profile"
            {...props}
        >
            <SimpleForm>
                {/* <TextInput source="nickname" validate={required()} /> */}
                <TextInput source="company" validate={required()} />
                
            </SimpleForm>
        </Edit>
    );
};

export default ProfileEdit;
